FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY client/package*.json ./

RUN npm install

# Bundle app source
COPY client/ .

EXPOSE 1234
CMD [ "npm", "start", "--", "--port", "1234" ]